[UserInfo]
user = "dummy"
tenantId = "dummy"
apiPassword = "dummy"

[Thread]
threadNum = 1
sleepSecondsAfterDeleteInstance = 1
sleepSecondsAfterDeleteFloatingIp = 1
sleepSecondsBeforeJointFloatingIp = 1

[Instance]
imageId = "dummy"